name: map
description: A utility to allow easy creation of maps.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  geolocator: ^8.0.1
  flutter_map: ^0.14.0